### ISSUE TITLE
Feature Request: Allow Setting Parameters (max_conns, etc.) through the YAML

### ISSUE THREAD

**Issue by helle** [nginxinc/nginx-asg-sync#1]
All parameters described here:

https://nginx.org/en/docs/http/ngx_http_upstream_module.html#server

should be configurable through the YAML file.

**Comment by pleshakov** [comment]
@helle 
Thanks for the feedback. Yes, it makes to include some of those parameters into the yaml. We will include this feature into the next release. However, we don't have a specific date for it yet.  
If it is blocking you, I can suggest adding those params in this line (https://github.com/nginxinc/nginx-asg-sync/blob/master/cmd/sync/nginx.go#L191), which creates a request string for adding a server to an upstream, and building your own packages.
