### ISSUE TITLE
Support basic auth in config

### ISSUE THREAD

**Issue by rickeyski** [nginxinc/nginx-asg-sync#15]
With the switch over to the new config api, the documented way of securing it is using http basic auth. This doesn't seem to be supported at all in the current cmd. Would it make sense to enable the nginx-asg-client to use basic auth params from the config file so the api isn't write available to the world? Thanks

**Comment by pleshakov** [comment]
@rickeyski 
for the case when an API client runs on the same machine as NGINX Plus, which is true for nginx-asg-sync, a better way to protect NGINX Plus API is to use a unix domain socket, and ensure that only NGINX Plus and  nginx-asg-sync can write to that socket. Unfortunately, this is not available in nginx-asg-sync.

To make NGINX Plus API inaccessible to the external clients, you configure NGINX Plus to listen on the local `127.0.0.1` address:
```nginx
server {
    listen 127.0.0.1:8080;

    location /api {
        api write=on;
    }
}
```
