### ISSUE TITLE
Autoscaled instances registered before active health checks take into effect

### ISSUE THREAD

**Issue by adybuxton** [nginxinc/nginx-asg-sync#16]
We have an issue where instances are being added to the upstream lists before they are actually ready. The active NGinx health checks that run every 5 seconds, are ignored for roughly the first 30 seconds after the instance has been added. This results in the services timing out for 30 secs until the active health check marks the new instance as 'down' whilst chef installs the services.

We've noticed that this solution also adds auto scaled instances regardless of state, so by setting a lifecyle hook to mark the instance as initially pending and then allowing it timing out after several minutes to the InService state (whilst the services are provisioning in the background), still results in the new instance being added immediately when a new instance spins up. 

Modifying the sync interval doesn’t make any difference in this scenario as an instance could be added towards the end of the sync interval and still show up immediately in the upstream list. 

Is this a limitation of the service or there other approaches to mitigate this? Is there a reason why there is a large delay before active health checks mark the services as down?

**Comment by adybuxton** [comment]
Thanks, i'll take a look. One thing that may be of additional value and flexibility is to allow instances with specific lifecycle hook states to be filtered from the returned instance list, for instance Pending:Wait to cover situations when the instance is told to wait for a finite time (ie for provisioning) before it transitions into the InService state.

**Comment by pleshakov** [comment]
implemented in https://github.com/nginxinc/nginx-asg-sync/pull/39
