### ISSUE TITLE
Feature Request: Support SetInstanceHealth to terminate failed ASG instances

### ISSUE THREAD

**Issue by cbarbour** [nginxinc/nginx-asg-sync#2]
We have an appliance we'd like to put behind Nginx using the asg-sync module. The appliance currently relies on ELB health checks to identify and mark failed instances. It would be useful if Nginx could provide this functionality without the need for an ELB.

Currently, [ASGs support 3 types of health checks](http://docs.aws.amazon.com/autoscaling/latest/userguide/healthcheck.html):

* EC2 Health checks which look for basic network connectivity, a soft watchdog, etc.
* ELB health checks via HTTP
* Custom health checks, via the [SetInstanceHealth API call](https://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_SetInstanceHealth.html).

For Nginx to mark an ASG instance as unhealthy, it simply needs to call the SetInstanceHealth API to change the instance state. This would completely eliminate the need for an ELB in our case. As of now, we have to have one even though it's not handling any traffic.

Also, If this can be implemented/supported by Nginx, we'd be more than happy to contributing a least permissive IAM policy.

**Comment by pleshakov** [comment]
@cbarbour 
I don't think this functionality fits into either NGINX or nginx-asg-sync. The purpose of nginx-asg-sync is to address only the discovery of Auto Scaling instances.
