### ISSUE TITLE
Allow multiple autoscaling groups per upstream

### ISSUE THREAD

**Issue by stephenbaugh** [nginxinc/nginx-asg-sync#3]
We use two auto scale groups per upstream (well we did with ELB), one for base on demand instances and then for spot instances.

Any chance this could be added as a feature to query more than one group?

Thanks

**Comment by pleshakov** [comment]
@stephenbaugh 
We don't have any plans to support it in the nearest future. However, it is possible. At minimum, It will require extending the `getAutoscalingGroup` [method](https://github.com/nginxinc/nginx-asg-sync/blob/master/cmd/sync/aws.go#L55) to support multiple groups. You can compile the modified nginx-asg-sync and build your own pacakges as described here -- https://github.com/nginxinc/nginx-asg-sync#building-a-software-package.

**Comment by boostchicken** [comment]
@stephenbaugh look at the PR I sent,  If you query the ASGs that way you can just add another tag filter and get many that way,  It also reduced API calls significantly for larger installs of NGINX

https://github.com/nginxinc/nginx-asg-sync/pull/6
