### ISSUE TITLE
Move from status to api module

### ISSUE THREAD

**Issue by rickeyski** [nginxinc/nginx-asg-sync#5]
Is there a planned timeline to move to the API module? The docs say the status module has been superseded. Thanks.

**Comment by pleshakov** [comment]
@rickeyski 
The status and upstream_conf APIs are planned to be removed from NGINX Plus in the second half of this year. We will migrate to use the new API module by that time. However, not any time soon.

**Comment by stephenbaugh** [comment]
Hi. I see the documentation now shows support for the api, but when I install nginx-asg-sync doesn't run. Does release 0.1-2 support the use of api? The release didn't seem to get updated at the same time? If not is there a new release available?

Thanks

**Comment by pleshakov** [comment]
@stephenbaugh 
0.1-2 doesn't support the new API.  

The support for the new API is currently available only in the `master` branch. We'll publish a new release (0.2) that will include the support for the new API later in July.

If you'd like to start using the new API right now, you can build the packages by yourself using the sources from the `master` branch.  Note that the packages will still have the 0.1-2 version, as we didn't yet change the version in the packages sources.

**Comment by dleavitt802** [comment]
Please add Ubuntu 18.04 to the Releases page https://github.com/nginxinc/nginx-asg-sync/releases

**Comment by Dean-Coakley** [comment]
Hi @dleavitt802
Ubuntu 18.04 is not a [currently supported](https://github.com/nginxinc/nginx-asg-sync#supported-operating-systems) release

If you have any more questions, or if you would like to request 18.04 support, feel free to [create a new issue](https://github.com/nginxinc/nginx-asg-sync/issues/new) and we will do our best to help

**Comment by Dean-Coakley** [comment]
Closing. [0.2-1 release](https://github.com/nginxinc/nginx-asg-sync/releases/tag/v0.2-1) is now available with the new api implemented: https://github.com/nginxinc/nginx-asg-sync/pull/7
